In [2]:
import numpy as np

In [3]:
np.random.rand(5,5)

array([[0.1510671 , 0.80238374, 0.40227251, 0.51452728, 0.28745932],
       [0.87918598, 0.78791749, 0.17742528, 0.25146921, 0.46078238],
       [0.58603467, 0.14161072, 0.28637426, 0.18741927, 0.90410234],
       [0.40390924, 0.20605427, 0.25634769, 0.54374631, 0.18066856],
       [0.66677648, 0.25822115, 0.10164471, 0.3745109 , 0.40094862]])

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [1]:
my_matrix = [[1,2,3],[4,5,6,],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
import numpy as np

In [4]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
my_list3 = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
]

In [7]:
np.array(my_list3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [16]:
np.random.rand(2)

array([0.52042948, 0.60578663])

In [17]:
np.random.rand(5,5)

array([[0.68970214, 0.3603114 , 0.40740638, 0.81720785, 0.54711427],
       [0.72180686, 0.77169624, 0.93988969, 0.24615423, 0.19946969],
       [0.64717587, 0.03359251, 0.7363716 , 0.79247361, 0.04467579],
       [0.47614155, 0.65865758, 0.57717844, 0.30845975, 0.34344749],
       [0.87816627, 0.37299929, 0.52443973, 0.86696996, 0.5984085 ]])

In [18]:
np.random.randn(2)

array([-0.21209204,  0.64991394])

In [19]:
np.random.randn(5,5)

array([[-0.87454695, -1.72442201, -0.89851901,  0.11836221, -0.0425418 ],
       [ 0.77307697, -0.43826437, -0.2352505 , -0.90424414,  0.75412651],
       [ 0.07859683,  1.1284575 , -0.94301456, -0.72498927,  1.46502792],
       [-0.28411005,  1.06889612, -0.21486411, -0.05761503, -1.57458154],
       [-1.83406323, -0.01992348, -0.08012714, -0.2540657 , -0.16464076]])

In [20]:
np.random.randint(1,100)

67

In [21]:
np.random.randint(1,100,10)

array([ 5, 39, 60, 73, 99, 10, 85, 63, 86, 41])

In [ ]:
mylist = [1,2,3]
array_1d = np.array(mylist)

mylist2 = [[1,2,3],[4,5,6],[7,8,9]]
array_2d = np.array(mylist2)

my_list3 = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
]
array_3d = np.array(my_list3)

In [48]:
array_1d.shape

(3,)

In [49]:
array_2d.shape

(3, 3)

In [1]:
array_3d.shape

NameError: name 'array_3d' is not defined

In [57]:
arr

AttributeError: module 'array' has no attribute 'shape'

In [54]:
arr.shape


AttributeError: module 'array' has no attribute 'shape'

In [55]:
arr.reshape(1,25)

AttributeError: module 'array' has no attribute 'reshape'

In [56]:
arr.reshape(1,25).shape

AttributeError: module 'array' has no attribute 'reshape'

In [59]:
arr.reshape(5,5)

AttributeError: module 'array' has no attribute 'reshape'

In [61]:
arr.reshape(25,1)

AttributeError: module 'array' has no attribute 'reshape'

In [62]:
arr.reshpe(25,1).shape

AttributeError: module 'array' has no attribute 'reshpe'

In [63]:
array_2d.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
array_2d.reshape(-1).shape

(9,)

In [65]:
array_3d.reshape(-1)

NameError: name 'array_3d' is not defined

In [66]:
array_3d.reshape(-1).shape

NameError: name 'array_3d' is not defined

In [67]:
ranarr

NameError: name 'ranarr' is not defined

In [68]:
ranarr.max()

NameError: name 'ranarr' is not defined

In [69]:
ranarr.argmac()

NameError: name 'ranarr' is not defined

In [70]:
ranarr.min()

NameError: name 'ranarr' is not defined

In [71]:
ranarr.argmin()

NameError: name 'ranarr' is not defined

In [72]:
arr.dtype

AttributeError: module 'array' has no attribute 'dtype'

In [73]:
arr11=np.linspace(0,10,10)
arr1.dtype

NameError: name 'arr1' is not defined

In [2]:
import numpy as np

In [6]:
x = np.arange(0,11)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
x[8]

8

In [9]:
x[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
x[0:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
x[-2]

9

In [12]:
x[0:10:2]

array([0, 2, 4, 6, 8])

In [13]:
x[0:5]=100
x

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
x = np.arange(0,11)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
slice_of_x = x[0:6]
slice_of_x

array([0, 1, 2, 3, 4, 5])

In [17]:
x[0:2]=100
x

array([100, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [18]:
x_slice = x[0:2]
x_slice

array([100, 100])

In [19]:
x

array([100, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [20]:
x_slice[:]=20
x_slice

array([20, 20])

In [21]:
x

array([20, 20,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
x_copy = x.copy()


In [23]:
x_copy [:] = 120
x_copy

array([120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120])

In [24]:
x %2 == 0

array([ True,  True,  True, False,  True, False,  True, False,  True,
       False,  True])

In [25]:
x_bool = x %2 == 0
x_bool

array([ True,  True,  True, False,  True, False,  True, False,  True,
       False,  True])

In [26]:
x[x_bool]

array([20, 20,  2,  4,  6,  8, 10])

In [27]:
x[x%2==0]

array([20, 20,  2,  4,  6,  8, 10])

In [28]:
a = 2
x[x%a==0]

array([20, 20,  2,  4,  6,  8, 10])

In [29]:
x


array([20, 20,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
[x[2],x[5],x[9]]

[2, 5, 9]

In [31]:
x[[2,5,9]]

array([2, 5, 9])

In [32]:
x[[5,9,2]]

array([5, 9, 2])

In [33]:
x_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
x_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
x_2d[[0,2]]

array([[ 5, 10, 15],
       [35, 40, 45]])

In [35]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [37]:
bool_arr = arr>4

In [38]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [39]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])